// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yred.Authentication.Relationals.Data.Contexts;

namespace DeathBringer.EntityFramework.Migrations
{
    [DbContext(typeof(DeathBringerDbContext))]
    [Migration("20190221110004_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeathBringer.Terminal.BaseClasses.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<int>("CategoriaAppartenenzaId");

                    b.Property<DateTime>("DataCreazioneRecord");

                    b.Property<DateTime>("DataProduzione");

                    b.Property<DateTime>("DataUltimaModifica");

                    b.Property<string>("Descrizione");

                    b.Property<byte[]>("Foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UtenteCreazioneRecord");

                    b.Property<string>("UtenteUltimaModificaRecord");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaAppartenenzaId");

                    b.ToTable("tabella_Prodotti");
                });

            modelBuilder.Entity("DeathBringer.Terminal.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCreazioneRecord");

                    b.Property<DateTime>("DataUltimaModifica");

                    b.Property<string>("Descrizione");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("UtenteCreazioneRecord");

                    b.Property<string>("UtenteUltimaModificaRecord");

                    b.HasKey("Id");

                    b.ToTable("tabella_Categorie");
                });

            modelBuilder.Entity("DeathBringer.Terminal.Entities.Prezzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Costo")
                        .HasMaxLength(255);

                    b.Property<DateTime>("DataCreazioneRecord");

                    b.Property<DateTime>("DataInizio");

                    b.Property<DateTime>("DataUltimaModifica");

                    b.Property<int>("ProdottoAssociatoId");

                    b.Property<double>("Sconto");

                    b.Property<string>("UtenteCreazioneRecord");

                    b.Property<string>("UtenteUltimaModificaRecord");

                    b.HasKey("Id");

                    b.HasIndex("ProdottoAssociatoId");

                    b.ToTable("tabella_Prezzo");
                });

            modelBuilder.Entity("DeathBringer.Terminal.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cap");

                    b.Property<string>("Citta");

                    b.Property<string>("Civico");

                    b.Property<string>("Cognome");

                    b.Property<DateTime>("DataCreazioneRecord");

                    b.Property<DateTime>("DataUltimaModifica");

                    b.Property<string>("Email");

                    b.Property<string>("Indirizzo");

                    b.Property<bool>("IsAdministrator");

                    b.Property<string>("Nome");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.Property<string>("UtenteCreazioneRecord");

                    b.Property<string>("UtenteUltimaModificaRecord");

                    b.HasKey("Id");

                    b.ToTable("tabella_Utenti");
                });

            modelBuilder.Entity("DeathBringer.Terminal.BaseClasses.Prodotto", b =>
                {
                    b.HasOne("DeathBringer.Terminal.Entities.Categoria", "CategoriaAppartenenza")
                        .WithMany("Prodotti")
                        .HasForeignKey("CategoriaAppartenenzaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DeathBringer.Terminal.Entities.Prezzo", b =>
                {
                    b.HasOne("DeathBringer.Terminal.BaseClasses.Prodotto", "ProdottoAssociato")
                        .WithMany("Prezzi")
                        .HasForeignKey("ProdottoAssociatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
