// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yred.Authentication.Relationals.Data.Contexts;

namespace DeathBringer.EntityFramework.Migrations
{
    [DbContext(typeof(DeathBringerDbContext))]
    partial class DeathBringerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeathBringer.Terminal.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cap");

                    b.Property<string>("Citta");

                    b.Property<string>("Civico");

                    b.Property<string>("Cognome");

                    b.Property<DateTime>("DataCreazioneRecord");

                    b.Property<DateTime>("DataUltimaModifica");

                    b.Property<string>("Email");

                    b.Property<string>("Indirizzo");

                    b.Property<bool>("IsAdministrator");

                    b.Property<string>("Nome");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.Property<string>("UtenteCreazioneRecord");

                    b.Property<string>("UtenteUltimaModificaRecord");

                    b.HasKey("Id");

                    b.ToTable("tabella_Utenti");
                });
#pragma warning restore 612, 618
        }
    }
}
